Resource_Group_Name               = "akash-rg"
Location_Name                     ="eastus"
Virtual_Network_Name              ="vnet"
Address_space                     =["10.1.0.0/16"]
Busniness_division                = "HR"
environment                       = "Dev"								  
Network_security_Name_app         ="Network_security_Name_app"
Subnet_Name_app                   = "appsubnet"
subnet_address_list__app          =["10.1.11.0/24"]
Network_security_Name_Bastion     ="Network_security_Name_Bastion"
Subnet_Name_bastion               ="bastionsubnet"
subnet_address_list__bastion      = ["10.1.100.0/24"]
Subnet_Name_db                    = "dbsubnet"
Network_security_Name_db          ="Network_security_Name_db"
subnet_address_list_db            =["10.1.21.0/24"]
Network_security_Name_web_server  ="Network_security_Name_web_server"
Subnet_Name_web_server            ="websubnet"
subnet_address_list_web_server    =["10.1.1.0/24"]